-- 0Gauge Recovery — inventory quantity ledger + invoice/outgoing-order
-- document types. Phase 1 of "scan-to-invoice": fuses barcode/photo
-- scanning into this app so a scan session can become a quote (unchanged,
-- existing flow), an invoice (new — printed, paid, tracked), a vendor
-- inventory receipt (new — no header document, just ledger rows), or an
-- outgoing order to another shop (new). See docs/INVENTORY_AND_SCANNING.md.
--
-- This is a real pivot from catalog_items' original "selling catalog, not
-- real-time inventory" framing (see docs/CATALOG_AND_PACKAGES.md) — the
-- user explicitly wants received/sold/transferred quantities tracked now.
-- quantity_on_hand defaults to 0 and is entirely additive/opt-in per item;
-- nothing about quoting requires it, same as before.

-- ---------------------------------------------------------------------------
-- catalog_items: quantity tracking + generated-code bookkeeping
-- ---------------------------------------------------------------------------

alter table public.catalog_items
  add column quantity_on_hand integer not null default 0,
  -- True when `upc` was generated by this app (GS1 in-store reserved range,
  -- see src/lib/upc.ts) rather than a real, looked-up manufacturer code.
  -- Drives both display ("Internal code" vs "UPC") and the label-print queue.
  add column upc_is_generated boolean not null default false,
  -- Null = still needs a label printed (only meaningful when upc_is_generated).
  add column label_printed_at timestamptz;

-- ---------------------------------------------------------------------------
-- invoices / invoice_items — a single finalized, itemized sale. Flat (no
-- tiers/options), unlike quotes, since by the time something is an invoice
-- staff have already decided what's being sold.
-- ---------------------------------------------------------------------------

create type invoice_status as enum ('draft', 'paid', 'void');

-- Broader than the existing `payment_method` enum (0004) on purpose — that
-- one is specifically for online deposit-payment links on a quote. An
-- invoice is usually paid in person, so this adds cash/card/other.
create type invoice_payment_method as enum ('cash', 'card', 'zelle', 'cashapp', 'venmo', 'paypal', 'link', 'other');

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete set null,
  -- Sequential per shop (1, 2, 3, ...), assigned by the trigger below — a
  -- human-friendly number to print/reference, distinct from the row's uuid.
  invoice_number integer not null,
  status invoice_status not null default 'draft',
  payment_method invoice_payment_method,
  payment_amount_cents bigint check (payment_amount_cents is null or payment_amount_cents >= 0),
  paid_at timestamptz,
  subtotal_cents bigint not null default 0 check (subtotal_cents >= 0),
  total_cents bigint not null default 0 check (total_cents >= 0),
  notes text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_id, invoice_number)
);

create index invoices_shop_idx on public.invoices (shop_id, created_at desc);
create index invoices_shop_status_idx on public.invoices (shop_id, status);

create trigger invoices_updated_at before update on public.invoices
  for each row execute function public.set_updated_at();

-- Assigns invoice_number = next per shop. Uses an advisory xact lock keyed
-- on the shop so two concurrent inserts for the same shop don't race to the
-- same number (the lock releases automatically at transaction end).
create or replace function public.assign_invoice_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(hashtext('invoice:' || new.shop_id::text));
  select coalesce(max(invoice_number), 0) + 1 into new.invoice_number
  from public.invoices where shop_id = new.shop_id;
  return new;
end;
$$;

create trigger invoices_assign_number before insert on public.invoices
  for each row execute function public.assign_invoice_number();

create table public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices (id) on delete cascade,
  -- Nullable: a custom line item (fee, misc part) has no catalog product
  -- behind it, same precedent as quote_items.category being nullable.
  catalog_item_id uuid references public.catalog_items (id) on delete set null,
  brand text,
  model text,
  name text not null,
  quantity integer not null default 1 check (quantity >= 1),
  unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
  category product_category,
  position integer not null default 0
);

create index invoice_items_invoice_idx on public.invoice_items (invoice_id);

-- ---------------------------------------------------------------------------
-- outgoing_orders / outgoing_order_items — stock sent to another shop.
-- Same shape as invoices minus payment; adds a destination name.
-- ---------------------------------------------------------------------------

create type outgoing_order_status as enum ('draft', 'sent');

create table public.outgoing_orders (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops (id) on delete cascade,
  order_number integer not null,
  destination_name text not null default '',
  status outgoing_order_status not null default 'draft',
  notes text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_id, order_number)
);

create index outgoing_orders_shop_idx on public.outgoing_orders (shop_id, created_at desc);

create trigger outgoing_orders_updated_at before update on public.outgoing_orders
  for each row execute function public.set_updated_at();

create or replace function public.assign_outgoing_order_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(hashtext('outgoing_order:' || new.shop_id::text));
  select coalesce(max(order_number), 0) + 1 into new.order_number
  from public.outgoing_orders where shop_id = new.shop_id;
  return new;
end;
$$;

create trigger outgoing_orders_assign_number before insert on public.outgoing_orders
  for each row execute function public.assign_outgoing_order_number();

create table public.outgoing_order_items (
  id uuid primary key default gen_random_uuid(),
  outgoing_order_id uuid not null references public.outgoing_orders (id) on delete cascade,
  catalog_item_id uuid references public.catalog_items (id) on delete set null,
  brand text,
  model text,
  name text not null,
  quantity integer not null default 1 check (quantity >= 1),
  category product_category,
  position integer not null default 0
);

create index outgoing_order_items_order_idx on public.outgoing_order_items (outgoing_order_id);

-- ---------------------------------------------------------------------------
-- stock_movements — append-only ledger. quantity_on_hand is derived from
-- this (kept in sync by apply_stock_movement below), not hand-edited.
-- ---------------------------------------------------------------------------

create type stock_movement_type as enum ('receiving', 'outgoing_order', 'sale', 'adjustment');

create table public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops (id) on delete cascade,
  catalog_item_id uuid not null references public.catalog_items (id) on delete cascade,
  movement_type stock_movement_type not null,
  -- Signed: positive for receiving/adjustment-up, negative for sale/outgoing_order.
  quantity_delta integer not null check (quantity_delta <> 0),
  unit_cost_cents bigint check (unit_cost_cents is null or unit_cost_cents >= 0),
  -- Vendor name (receiving) or destination shop name (outgoing_order), free text.
  counterparty_name text,
  source_invoice_id uuid references public.invoices (id) on delete set null,
  source_outgoing_order_id uuid references public.outgoing_orders (id) on delete set null,
  note text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index stock_movements_shop_created_idx on public.stock_movements (shop_id, created_at desc);
create index stock_movements_item_idx on public.stock_movements (catalog_item_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS — same shop-scoped pattern as catalog_items_all / package_templates_all.
-- ---------------------------------------------------------------------------

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.outgoing_orders enable row level security;
alter table public.outgoing_order_items enable row level security;
alter table public.stock_movements enable row level security;

create policy invoices_all on public.invoices
  for all to authenticated
  using (public.is_shop_member(shop_id))
  with check (public.is_shop_member(shop_id));

create policy invoice_items_all on public.invoice_items
  for all to authenticated
  using (exists (select 1 from public.invoices i where i.id = invoice_id and public.is_shop_member(i.shop_id)))
  with check (exists (select 1 from public.invoices i where i.id = invoice_id and public.is_shop_member(i.shop_id)));

create policy outgoing_orders_all on public.outgoing_orders
  for all to authenticated
  using (public.is_shop_member(shop_id))
  with check (public.is_shop_member(shop_id));

create policy outgoing_order_items_all on public.outgoing_order_items
  for all to authenticated
  using (exists (select 1 from public.outgoing_orders o where o.id = outgoing_order_id and public.is_shop_member(o.shop_id)))
  with check (exists (select 1 from public.outgoing_orders o where o.id = outgoing_order_id and public.is_shop_member(o.shop_id)));

-- Read-only for shop members via RLS — every write goes through
-- apply_stock_movement() below so quantity_on_hand can never drift out of
-- sync with the ledger (no direct insert/update/delete policy on purpose).
create policy stock_movements_select on public.stock_movements
  for select to authenticated
  using (public.is_shop_member(shop_id));

-- ---------------------------------------------------------------------------
-- apply_stock_movement — the only way quantity_on_hand changes. Inserts the
-- ledger row and updates the item's quantity atomically (one function
-- invocation = one transaction), avoiding read-modify-write races when two
-- staff scan/receive/sell at the same time.
-- ---------------------------------------------------------------------------

create or replace function public.apply_stock_movement(
  p_catalog_item_id uuid,
  p_movement_type stock_movement_type,
  p_quantity_delta integer,
  p_unit_cost_cents bigint default null,
  p_counterparty_name text default null,
  p_source_invoice_id uuid default null,
  p_source_outgoing_order_id uuid default null,
  p_note text default null
)
returns public.stock_movements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shop_id uuid;
  v_movement public.stock_movements;
begin
  select shop_id into v_shop_id from public.catalog_items where id = p_catalog_item_id;
  if v_shop_id is null then
    raise exception 'Unknown catalog item';
  end if;
  if not public.is_shop_member(v_shop_id) then
    raise exception 'Not a member of this shop';
  end if;

  insert into public.stock_movements (
    shop_id, catalog_item_id, movement_type, quantity_delta, unit_cost_cents,
    counterparty_name, source_invoice_id, source_outgoing_order_id, note, created_by
  ) values (
    v_shop_id, p_catalog_item_id, p_movement_type, p_quantity_delta, p_unit_cost_cents,
    p_counterparty_name, p_source_invoice_id, p_source_outgoing_order_id, p_note, auth.uid()
  )
  returning * into v_movement;

  update public.catalog_items
  set quantity_on_hand = quantity_on_hand + p_quantity_delta
  where id = p_catalog_item_id;

  return v_movement;
end;
$$;

grant execute on function public.apply_stock_movement to authenticated;
