import type {
  Appointment,
  AppointmentSource,
  Bay,
  BusinessHoursDay,
  CatalogItem,
  Customer,
  EmailMessage,
  Employee,
  FinancingOffer,
  ImportSource,
  Invoice,
  InvoicePaymentMethod,
  InventoryDevice,
  OptionKind,
  PackageTemplate,
  PackageTemplateSource,
  PaymentMethod,
  PriceKind,
  ProductApprovalStatus,
  ProductAvailability,
  ProductCategory,
  PublicQuote,
  Quote,
  QuoteBundle,
  QuoteEvent,
  QuoteOption,
  QuoteResponse,
  QuoteStatus,
  ResponseType,
  ScheduleException,
  Service,
  ServiceDurationOverride,
  Shop,
  StockMovement,
  StockMovementType,
  TemplateType,
  TintBodyStyle,
  VehicleType,
  WindowTintConfig,
} from '../types'

// Single abstraction both modes implement. Demo mode persists to localStorage;
// production mode talks to Supabase (tables + RPCs + Edge Function).

export interface NewQuoteInput {
  customer: {
    firstName: string
    lastName: string | null
    email: string
    phone: string | null
    vehicleYear: number | null
    vehicleMake: string | null
    vehicleModel: string | null
    vehicleTrim: string | null
    source: string | null
    emailContactPermissionConfirmed: boolean
  }
  quote: {
    internalNotes: string | null
    expirationDate: string | null
    nextFollowUpAt: string | null
    windowTints: WindowTintConfig[]
    /** Staff opt-in: show one extra "everything included" total line (main + every add-on). Off by default. */
    showFullAddonTotal?: boolean
  }
  /** Exactly one entry should carry optionKind 'main' — every write path (NewQuotePage, ScanWorkspacePage, demo seeds) guarantees this; see src/lib/quotePricing.ts for how a missing main is tolerated downstream. */
  options: Array<{
    optionKind: OptionKind
    name: string
    description: string
    /** Full price for a 'main' option; the *incremental* price on top of the main package for an 'addon'. */
    priceCents: number
    laborIncluded: boolean
    depositPaymentMethod: PaymentMethod | null
    depositPaymentHandle: string | null
    depositAmountCents: number | null
    /** Which universal configuration (e.g. 'bass_2x8') this was built against, if any. Optional — the fast/visual builder that sets this is a later phase. */
    configId?: string | null
    items: Array<{
      brand: string | null
      model: string | null
      name: string
      quantity: number
      description: string | null
      /** Optional — lets this item fill a configuration slot (see src/lib/audioConfigs.ts). */
      category?: ProductCategory | null
      /** Snapshotted from the catalog item/candidate this was added from, if any. */
      imageUrl?: string | null
    }>
  }>
}

export interface SendEmailResult {
  ok: boolean
  status: 'sent' | 'demo_sent' | 'failed'
  message: string
}

export interface ShopSettingsPatch {
  name?: string
  phone?: string
  email?: string
  replyToEmail?: string
  address?: string
  website?: string | null
  logoUrl?: string | null
  primaryColor?: string
  defaultPaymentMethod?: PaymentMethod | null
  defaultPaymentHandle?: string | null
  /** Replaces the whole list — Settings always sends the full set, never a delta. */
  financingOffers?: FinancingOffer[]
  quoteExpirationDays?: number
  followUpScheduleDays?: number[]
  quoteDisclaimer?: string
  defaultLowStockThreshold?: number
  lowStockAlertEmail?: string | null
  bookingDepositCents?: number | null
  autoFollowUpEnabled?: boolean
  contributesToGlobalCatalog?: boolean
}

export interface NewCatalogItemInput {
  brand: string | null
  model: string | null
  name: string
  defaultPriceCents: number | null
  // Everything below is optional — the manual "Product Catalog" settings
  // form only ever sets the fields above. These exist so a future importer
  // (Shopify, AI photo onboarding — both deferred, see
  // docs/CATALOG_AND_PACKAGES.md) can populate a full product record through
  // this same interface, rather than a parallel one.
  category?: ProductCategory | null
  description?: string | null
  sku?: string | null
  upc?: string | null
  msrpCents?: number | null
  promoPriceCents?: number | null
  minStaffPriceCents?: number | null
  costCents?: number | null
  priceSourceUrl?: string | null
  priceSourceName?: string | null
  priceKind?: PriceKind | null
  imageUrl?: string | null
  imageSourceUrl?: string | null
  sourceUrl?: string | null
  specs?: Record<string, unknown> | null
  active?: boolean
  availability?: ProductAvailability
  importSource?: ImportSource
  externalSourceProductId?: string | null
  identificationConfidence?: number | null
  approvalStatus?: ProductApprovalStatus
  /** Per-item low-stock override; omit/null to fall back to the shop default (src/lib/inventory.ts). */
  lowStockThreshold?: number | null
  /** True when the value in `upc` was generated by this app (src/lib/sku.ts's generateSku) rather than a real, looked-up manufacturer code. */
  upcIsGenerated?: boolean
}

export interface NewPackageTemplateInput {
  name: string
  description: string
  configId: string | null
  vehicleTypes: VehicleType[]
  installedPriceCents: number | null
  laborIncluded: boolean
  source: PackageTemplateSource
  /** Omit to default to 'pending_review' — only an owner/manager can save one already-approved. */
  approvalStatus?: ProductApprovalStatus
  sourceQuoteId?: string | null
  sourceQuoteOptionId?: string | null
  items: Array<{
    brand: string | null
    model: string | null
    name: string
    quantity: number
    description: string | null
    category: ProductCategory | null
    imageUrl: string | null
  }>
}

/**
 * Records one stock-quantity change (a scan-to-invoice sale, a vendor
 * receipt, an outgoing order, or a manual adjustment) — see StockMovement.
 * This is the only way quantityOnHand on a catalog item changes; both repo
 * implementations must update it atomically alongside the ledger row (in
 * production, via the apply_stock_movement RPC — see migration 0011).
 */
export interface NewStockMovementInput {
  catalogItemId: string
  movementType: StockMovementType
  /** Signed: positive for receiving/adjustment-up, negative for sale/outgoing_order. */
  quantityDelta: number
  unitCostCents?: number | null
  /** Vendor name (receiving) or destination shop name (outgoing_order), free text. */
  counterpartyName?: string | null
  sourceInvoiceId?: string | null
  sourceOutgoingOrderId?: string | null
  note?: string | null
}

/**
 * A single finalized, itemized sale — the scan workspace's "invoice"
 * document type. Created as 'draft'; markInvoicePaid() is what actually
 * moves stock (a 'sale' movement per line item with a catalogItemId) —
 * creating the invoice alone never touches quantityOnHand, so a draft can
 * still be freely edited or abandoned before anything's really sold.
 */
export interface NewInvoiceInput {
  customerId?: string | null
  notes?: string | null
  /** 0-1, e.g. 0.0825 for 8.25%. Applied only to taxable line items — see items[].taxable. Omit/0 for no tax. */
  taxRate?: number
  discountCents?: number
  /** Walk-in customer details typed at sale time — not a persisted Customer record. */
  customerName?: string | null
  customerPhone?: string | null
  customerEmail?: string | null
  customerAddress?: string | null
  vehicleYear?: number | null
  vehicleMake?: string | null
  vehicleModel?: string | null
  items: Array<{
    /** Null for a one-off/custom line item with no catalog product behind it. */
    catalogItemId: string | null
    brand: string | null
    model: string | null
    name: string
    quantity: number
    unitPriceCents: number
    category?: ProductCategory | null
    discountPercent?: number
    /** Defaults true — set false for a line that shouldn't count toward taxRate (e.g. labor, where the jurisdiction doesn't tax it). */
    taxable?: boolean
  }>
}

/**
 * Result of scanning/typing a barcode: either it matches something already
 * in this shop's catalog (the common case once a shop has scanned a
 * product once before), an external UPC database has it with enough
 * confidence to auto-add (production only — demo mode never makes the
 * real network call), a lower-confidence/AI-derived candidate list needs
 * staff to pick one (carried here directly — see the 'candidates' case
 * below), or nothing knows about it at all.
 */
// ---------------------------------------------------------------------------
// Booking (staff side — see docs/MVP_PLAN.md §5, src/lib/scheduling.ts).
// The public/anonymous side (get_public_booking_page, book_appointment,
// get_public_appointment, cancel_appointment_public) is deliberately NOT
// part of this interface — it's resolved by src/data/publicBooking.ts, the
// same split publicQuote.ts already uses for the anonymous quote surface.
// ---------------------------------------------------------------------------

export interface NewServiceInput {
  name: string
  description: string | null
  durationMinutes: number
  priceCents: number | null
  durationOverrides: ServiceDurationOverride[]
}

export interface NewAppointmentInput {
  bayId: string
  /** Existing customer (from a quote, or picked from the customer list) — mutually exclusive with the raw fields below. */
  customerId?: string
  customerFirstName?: string
  customerLastName?: string | null
  customerEmail?: string | null
  customerPhone?: string | null
  source: AppointmentSource
  startsAt: string
  bodyStyle: TintBodyStyle | null
  notes: string | null
  sourceQuoteId?: string | null
  services: Array<{ serviceId: string | null; name: string; durationMinutes: number; priceCents: number | null }>
}

export type UpcLookupResult =
  | { source: 'catalog'; catalogItem: CatalogItem }
  | { source: 'external'; name: string | null; brand: string | null; unitPriceCents: number | null; imageUrl: string | null; upc: string }
  /**
   * Same ranked candidates a follow-up resolveProduct({kind:'barcode'})
   * call would return — carried through directly from the one resolution
   * this method already ran, so the caller (ScanWorkspacePage) never has
   * to make a second network round-trip just to re-fetch what this call
   * already had. A second resolveProduct call would technically hit the
   * server-side cache and skip the AI/UPCitemdb work, but it's still a
   * full extra HTTP request + auth + membership check — real, noticeable
   * latency on every barcode that isn't an instant catalog/high-confidence
   * hit, which is the whole point of scanning fast.
   */
  | { source: 'candidates'; candidates: ProductResolutionCandidate[]; retainedInput: string }
  | { source: 'not_found' }

/**
 * One AI+web-search candidate for a partially-typed SKU/model/name (e.g.
 * "NA-12F") when staff are adding a new catalog product — see
 * ProductSuggestField. Deliberately loose/optional-feeling even though every
 * field is present: the model is told to prefer returning fewer results (or
 * none) over guessing, so any field can come back null.
 */
export interface ProductSuggestion {
  name: string
  brand: string | null
  model: string | null
  unitPriceCents: number | null
  imageUrl: string | null
  sourceUrl: string | null
}

// ---------------------------------------------------------------------------
// Universal product resolver — the one canonical, typed contract behind
// barcode lookup, typed search, and (later) photo lookup. See
// docs/PRODUCT_RESOLVER.md. lookupProductByUpc/lookupProductSuggestions
// above keep their existing narrower shapes for backward compatibility with
// already-shipped call sites (ScanWorkspacePage, ProductSuggestField) — both
// now delegate to resolveProduct() underneath rather than making their own
// separate external calls.
// ---------------------------------------------------------------------------

/** Where a resolved candidate's data actually came from — never conflated with "this shop's own catalog," which is checked locally before resolveProduct is ever called. */
export type ProductResolutionSource = 'resolution_cache' | 'verified_web_source' | 'ai_extracted'

/** Whether a reference price is MSRP, a verified retail price, or unclear — distinct from a shop's own selling price/cost, which a candidate never carries (see CatalogItem.defaultPriceCents/costCents for that). */
export type ProductPriceKind = 'msrp' | 'retail' | 'unknown'

export type ProductConfidenceLevel = 'high' | 'probable' | 'low'

/**
 * One ranked candidate identity for a scanned barcode or typed query that
 * didn't match anything already in this shop's catalog. Always a
 * *suggestion* — nothing here is written to the shop's catalog or cart
 * until staff explicitly act on it (see ScanWorkspacePage's confirmation
 * UI). referencePriceCents is a reference/market price, never a shop's own
 * confirmed selling price — the two are never overwritten by each other.
 */
export interface ProductResolutionCandidate {
  id: string
  source: ProductResolutionSource
  brand: string | null
  model: string | null
  name: string
  /** Free-text category hint (e.g. "car subwoofer") — not a raw ProductCategory value; map it with the existing guessCategoryFromName heuristic rather than trusting an AI-invented enum value. */
  categoryHint: string | null
  upc: string | null
  imageUrl: string | null
  referencePriceCents: number | null
  priceKind: ProductPriceKind
  priceSourceUrl: string | null
  priceSourceName: string | null
  /** 0-1 self-reported confidence, already discounted server-side for things like an unconfirmed barcode match. */
  confidence: number
  confidenceLevel: ProductConfidenceLevel
  /** Short human-readable reasons supporting this match. */
  evidence: string[]
  /** Things staff should double-check before trusting this candidate (e.g. "barcode not directly confirmed"). */
  warnings: string[]
}

/**
 * All three kinds prefer OpenAI (if OPENAI_API_KEY is set) and fall back
 * to Claude (if ANTHROPIC_API_KEY is set instead) — see resolve-product/
 * index.ts's resolveViaAi/resolveViaVision. 'photo' ports its *method*
 * (image + web_search + structured output, one call) from
 * car-audio-inventory's (this app's sister app) production vision route,
 * which is Claude-only there; this app runs the same combination through
 * OpenAI's Responses API too now, since that's not documented as
 * unsupported and OpenAI is the funded provider. Same graceful
 * degradation for all three either way — no funded key for the relevant
 * provider just means no candidates, never an error.
 */
export type ProductResolveRequest =
  /**
   * `brandHint` is the shop's current "brand lock" (see
   * src/lib/productSearch.ts) — the single biggest lever on result quality
   * for a manufacturer whose barcodes were never published anywhere. A bare
   * unpublished code can never match anything online; "Nemesis Audio
   * NA-12F" usually finds the manufacturer's own product page.
   *
   * `fast` skips the AI/web step and answers from the cache + UPCitemdb
   * only (~1s instead of 15-30s). The scan flow uses it so an unknown code
   * fails fast and staff can start typing what the box is, rather than
   * waiting out a search that was never going to resolve it. An empty fast
   * result is never cached, so a later full lookup still does the real work.
   */
  | { kind: 'barcode'; code: string; brandHint?: string | null; fast?: boolean }
  | { kind: 'text'; query: string; brandHint?: string | null }
  | { kind: 'photo'; imageBase64: string; mediaType: 'image/jpeg' | 'image/png' | 'image/webp' }

export interface ProductResolveResult {
  candidates: ProductResolutionCandidate[]
  /** The original code/query, always returned — even an empty-candidates result never loses what was scanned/typed, so the caller can fall back to a custom item with it prefilled. */
  retainedInput: string
  /**
   * False when the backend has no AI provider key funded, so nothing actually
   * looked the product up. Without this an unconfigured install is
   * indistinguishable from a genuine miss — both come back with zero
   * candidates — and a shop concludes lookup is broken. Demo mode reports
   * true: its results are canned, not absent.
   */
  aiConfigured: boolean
  /**
   * Set when a provider key IS funded but the call to it failed — a wrong
   * model name, an account out of credit, a revoked key, a network timeout.
   * Carries a short, safe summary ("OpenAI returned 404 (model_not_found)"),
   * never the provider's raw body, which can quote the request back.
   *
   * `aiConfigured` alone was not enough: with a key set, a broken provider and
   * a genuine miss both come back with zero candidates and `aiConfigured:
   * true`, so a shop whose key is present but not working is told to look for
   * a better photo forever. Null on a healthy lookup and on cached hits, where
   * no provider was asked anything.
   */
  aiError: string | null
  /**
   * True when the scanned code is one no public database can ever hold — a
   * store-assigned GS1 prefix, an internal item number, a bare part number —
   * so nothing was queried and nothing could have been found.
   *
   * Distinct from an ordinary empty result, and the distinction is the whole
   * point: "we searched everywhere and found nothing" sends staff hunting for
   * a better scan, while "there is nothing to search" sends them to the one
   * action that works — type the model, which binds the code to it for good.
   * See src/lib/barcodeIdentity.ts.
   */
  unresolvableBarcode: boolean
}

/**
 * Typing a model number is the primary intake path, and it used to fail
 * completely silently: the dropdown just said "No matches found" whether the
 * search genuinely came up empty, no AI key was funded, or the provider
 * rejected the call. Carrying the same two diagnostic fields the photo path
 * already had means the typed path can say which of the three happened.
 */
export interface ProductSuggestionResult {
  suggestions: ProductSuggestion[]
  aiConfigured: boolean
  aiError: string | null
}

/**
 * What a product-lookup self-test found out about this deployment.
 *
 * Every way lookup can be broken — no key, a key with no access to the
 * configured model, an unavailable tool identifier, a function that was never
 * deployed — produces the same empty candidate list from the outside. This
 * turns that into an answer someone can read and act on without opening Edge
 * Function logs.
 */
export interface ProductLookupSelfTest {
  ok: boolean
  /**
   * True/false when the backend actually told us, **null when we could not
   * find out** — the call never got far enough to ask.
   *
   * Null is the important state and it used to be missing. Every transport
   * failure reported `false`, so a request that never reached the function at
   * all rendered as "no AI provider key is set" — sending an owner who had
   * just set a key off to set it again. A diagnostic that guesses is worse
   * than no diagnostic.
   */
  aiConfigured: boolean | null
  provider: 'openai' | 'anthropic' | null
  /** The model actually used, after any override or auto-discovery. */
  model: string | null
  /** Which fallback level produced the answer — 1 is the richest. */
  rung: number | null
  rungLabel: string | null
  candidateCount: number
  /** The name of the first product found, as proof it really worked. */
  sample: string | null
  elapsedMs: number | null
  aiError: string | null
  /**
   * True when the answer came from the resolution cache rather than a live
   * provider call. A cache hit still proves the pipeline worked at some point,
   * but it says nothing about whether the key works *now* — so it is reported
   * rather than counted as a clean pass.
   */
  cached: boolean
  /** The deployed function's contract version, when it is new enough to report one. */
  functionVersion: number | null
}

/**
 * A product from the shared catalog. Public facts only — the shared table
 * holds nothing else by construction (see supabase/migrations/0026).
 */
export interface GlobalProductMatch {
  id: string
  barcode: string | null
  brand: string | null
  model: string | null
  name: string
  category: ProductCategory | null
  specs: Record<string, unknown> | null
  /** Manufacturer/web list price — never any shop's selling price or cost. */
  referencePriceCents: number | null
  priceKind: PriceKind | null
  imageUrl: string | null
  sourceUrl: string | null
  /** How many shops independently arrived at this record — the trust signal. */
  contributionCount: number
  /** Curated by a platform admin; outranks automatic contributions. */
  verified: boolean
}

export interface ShopifyImportOptions {
  /** Resume a prior run — pass back the nextCursor from its result. */
  afterCursor?: string | null
  /** Let Shopify's price win even over a price a staff member edited locally since the last sync. Defaults to false (never clobber a local edit). */
  overwriteLocalPrices?: boolean
}

export interface ShopifyImportResult {
  created: number
  updated: number
  unchanged: number
  skipped: number
  failed: number
  errors: Array<{ product: string; message: string }>
  hasMore: boolean
  nextCursor: string | null
}

export interface DataRepository {
  readonly mode: 'demo' | 'production'

  getShop(): Promise<Shop>
  updateShop(patch: ShopSettingsPatch): Promise<Shop>
  listEmployees(): Promise<Employee[]>

  listCatalogItems(): Promise<CatalogItem[]>
  createCatalogItem(input: NewCatalogItemInput): Promise<CatalogItem>
  updateCatalogItem(itemId: string, input: NewCatalogItemInput): Promise<CatalogItem>
  deleteCatalogItem(itemId: string): Promise<void>
  /** Owner/manager only in production — imports one page of the shop's Shopify catalog. Never call in demo mode (see docs/CATALOG_AND_PACKAGES.md). */
  runShopifyImport(options?: ShopifyImportOptions): Promise<ShopifyImportResult>

  /** Records a ledger entry and atomically updates the item's quantityOnHand. Returns the updated item alongside the recorded movement. */
  recordStockMovement(input: NewStockMovementInput): Promise<{ movement: StockMovement; catalogItem: CatalogItem }>
  /** Full shop history, or just one item's, newest first. */
  listStockMovements(catalogItemId?: string): Promise<StockMovement[]>
  /**
   * The spot-check flow (/app/inventory/check): always stamps lastCountedAt
   * to now; additionally records one 'adjustment' stock movement (and
   * returns it) only when newQuantity differs from the item's current
   * quantityOnHand — confirming a count that already matches touches no
   * ledger row.
   */
  markCounted(catalogItemId: string, newQuantity: number): Promise<{ catalogItem: CatalogItem; movement: StockMovement | null }>
  /**
   * Uploads a camera-captured photo (base64 JPEG, no data: prefix) and
   * returns a URL suitable for CatalogItem.imageUrl. Production stores it
   * in the shop-product-photos bucket (migration 0017); demo mode returns
   * a data: URI directly — no network call, but still a real, persistable
   * image, unlike lookupProductByUpc/resolveProduct's simulated results.
   */
  uploadProductPhoto(base64Jpeg: string): Promise<string>
  /**
   * Generates a scannable Code-128 SKU (src/lib/sku.ts) for a product with
   * no findable manufacturer barcode — the "quick add" path. Guaranteed
   * unique within the shop's catalog at call time (never assigned to an
   * item automatically; callers pass the result into createCatalogItem's
   * upc/sku fields).
   */
  generateSku(brand: string | null, model: string): Promise<string>
  /** Stamps labelPrintedAt so a printed item drops out of the label queue. */
  markLabelPrinted(catalogItemId: string): Promise<void>

  /** Local catalog match by UPC/SKU only — lookupProductByUpc below wraps this with an external-lookup fallback. */
  findCatalogItemByCode(code: string): Promise<CatalogItem | null>
  /**
   * Local catalog first, then (production only) an external UPC database.
   * `options.fast` stops there instead of falling through to the AI/web
   * search — see ProductResolveRequest. `options.brandHint` scopes any
   * search that does run to the brand currently being received.
   */
  lookupProductByUpc(code: string, options?: { fast?: boolean; brandHint?: string | null }): Promise<UpcLookupResult>
  /** AI+web-search autocomplete for a partially-typed SKU/model/name when adding a new catalog product. `brandHint` scopes the search to the brand being received. Demo mode never makes a real call — always resolves []. Production degrades to [] on any failure rather than throwing, same pattern as lookupProductByUpc. Delegates to resolveProduct() underneath. */
  lookupProductSuggestions(query: string, brandHint?: string | null): Promise<ProductSuggestionResult>
  /** Ask the backend whether product lookup actually works right now, and why not if it doesn't. */
  testProductLookup(): Promise<ProductLookupSelfTest>
  /**
   * Products other shops have already identified.
   *
   * Checked before any web/AI call: a product one shop paid to resolve should
   * be free for the next, which is the entire point of the shared catalog.
   * Never throws — a shared-catalog outage must not block manual entry.
   */
  searchGlobalProducts(query: string): Promise<GlobalProductMatch[]>
  /**
   * The universal resolver: called when a barcode or typed query doesn't
   * match anything already in this shop's catalog. Never throws and never
   * dead-ends — an empty candidate list is a valid, safe result (caller
   * falls back to a custom/temporary item using retainedInput). Demo mode
   * never makes a real AI/web call — see DemoRepository for its
   * deterministic simulated outcomes.
   */
  resolveProduct(request: ProductResolveRequest): Promise<ProductResolveResult>

  listInvoices(): Promise<Invoice[]>
  getInvoice(invoiceId: string): Promise<Invoice | null>
  /** Always created as 'draft' — never touches stock. */
  createInvoice(input: NewInvoiceInput): Promise<Invoice>
  /** Marks paid and records one 'sale' stock movement per line item that has a catalogItemId. */
  markInvoicePaid(invoiceId: string, paymentMethod: InvoicePaymentMethod, paymentAmountCents: number): Promise<Invoice>
  /** Emails a rendered copy of the invoice (recipientEmail is typed at send time — see ScanWorkspacePage — not a persisted Customer record). Never fakes real delivery in demo mode. */
  sendInvoiceEmail(invoiceId: string, recipientEmail: string, recipientName?: string): Promise<SendEmailResult>

  listPackageTemplates(): Promise<PackageTemplate[]>
  createPackageTemplate(input: NewPackageTemplateInput): Promise<PackageTemplate>
  /** Approve/reject a pending package. Enforced owner/manager-only at the DB layer (RLS trigger) in production. */
  setPackageTemplateApproval(templateId: string, status: ProductApprovalStatus): Promise<void>
  deletePackageTemplate(templateId: string): Promise<void>

  listQuoteBundles(): Promise<QuoteBundle[]>
  getQuoteBundle(quoteId: string): Promise<QuoteBundle | null>
  createQuote(input: NewQuoteInput): Promise<Quote>
  /**
   * Rewrites an existing quote from the same shape createQuote takes — the
   * edit form is the create form, so it hands back a whole quote rather
   * than a patch. Customer details and quote fields are updated in place;
   * options and their items are **fully replaced** (deleted and reinserted),
   * since the form has no concept of a per-option identity to diff against.
   *
   * Deliberately preserves everything that isn't the staff's to re-edit:
   * the public token (already-sent links keep working), status, send
   * history, events, and responses. Editing a quote is correcting what it
   * says, not restarting its lifecycle.
   */
  updateQuote(quoteId: string, input: NewQuoteInput): Promise<Quote>
  /** Permanently deletes a quote. Options/items/events/responses/emails go with it via on-delete-cascade. */
  deleteQuote(quoteId: string): Promise<void>

  /** Staff status actions: booked, deposit paid, won (with amount), lost. */
  setQuoteStatus(quoteId: string, status: QuoteStatus, wonAmountCents?: number | null): Promise<void>
  rescheduleFollowUp(quoteId: string, nextFollowUpAt: string | null): Promise<void>
  setFollowUpAllowed(quoteId: string, allowed: boolean): Promise<void>
  markContacted(quoteId: string): Promise<void>
  updateInternalNotes(quoteId: string, notes: string | null): Promise<void>
  /** Staff opt-in toggle: show a "main + every add-on" grand total alongside the per-add-on incremental pricing. */
  setShowFullAddonTotal(quoteId: string, show: boolean): Promise<void>

  /** Sends (or demo-sends) an email after eligibility passes. Never fakes real delivery. */
  sendEmail(quoteId: string, templateType: TemplateType): Promise<SendEmailResult>

  // Anonymous public-quote surface (RPC-backed in production).
  getPublicQuote(publicToken: string): Promise<PublicQuote | null>
  /**
   * Records a real customer view — but only when deliveryToken matches the
   * specific token embedded in an actually-sent email for this quote. A
   * null deliveryToken (the bare link staff use for "Open quote"/"Copy
   * link") is always a no-op — dashboard previews must never mark a quote
   * opened. See docs/QUOTE_TRACKING.md.
   */
  recordPublicView(publicToken: string, deliveryToken: string | null): Promise<void>
  submitPublicResponse(
    publicToken: string,
    responseType: ResponseType,
    optionId: string | null,
    message: string | null,
  ): Promise<void>
  optOutPublicQuote(publicToken: string): Promise<void>

  // ---------------------------------------------------------------------
  // Shared-device inventory access (migration 0017). Joining a shop by
  // code happens *before* a shop-scoped repository exists (see /join,
  // which calls the join_shop_with_access_code RPC directly — mirrors how
  // OnboardingPage calls create_shop_with_owner directly), so it isn't a
  // DataRepository method. These three are owner/manager actions taken
  // from within an already-loaded shop (Settings), so they are.
  // ---------------------------------------------------------------------

  /** Owner/manager only. Generates a fresh code, revokes every existing 'inventory' device, and returns the new plaintext code — shown exactly once, never re-readable after this call returns. */
  rotateStaffAccessCode(): Promise<string>
  /** Every phone/tablet/PC currently joined via the shop's access code, newest first. */
  listInventoryDevices(): Promise<InventoryDevice[]>
  /** Revokes one joined device without rotating the shared code — every other device stays signed in. */
  revokeInventoryDevice(membershipId: string): Promise<void>

  // ---------------------------------------------------------------------
  // Booking (staff side). See the NewServiceInput/NewAppointmentInput
  // comment above for why the public/anonymous side isn't here.
  // ---------------------------------------------------------------------

  listServices(): Promise<Service[]>
  saveService(serviceId: string | null, input: NewServiceInput): Promise<Service>
  deleteService(serviceId: string): Promise<void>
  listBays(): Promise<Bay[]>
  saveBay(bayId: string | null, name: string): Promise<Bay>
  deleteBay(bayId: string): Promise<void>
  listBusinessHours(): Promise<BusinessHoursDay[]>
  saveBusinessHours(hours: BusinessHoursDay[]): Promise<BusinessHoursDay[]>
  listScheduleExceptions(): Promise<ScheduleException[]>
  saveScheduleException(exceptionId: string | null, ex: Omit<ScheduleException, 'id' | 'shopId'>): Promise<ScheduleException>
  deleteScheduleException(exceptionId: string): Promise<void>
  /** Appointments starting in [rangeStart, rangeEnd) — both ISO timestamps. Used by the calendar view; keep the range tight (a day or a week), not "all of history". */
  listAppointments(rangeStart: string, rangeEnd: string): Promise<Appointment[]>
  /** Staff-side booking — direct create, no availability RPC (the exclusion constraint on `appointments` is what actually prevents a double-book; this call fails loudly if the chosen bay/time is already taken). */
  createAppointment(input: NewAppointmentInput): Promise<Appointment>
  setAppointmentStatus(appointmentId: string, status: Appointment['status']): Promise<void>
  /**
   * Move an appointment to a new time and/or bay, keeping the record.
   *
   * Cancel-and-rebook was the only way to do this, and it loses the history
   * AND mints a new `public_token` — which silently breaks the manage link
   * already sitting in the customer's inbox. Rescheduling in place keeps both.
   *
   * Needs no new migration: migration 0021's `appointments_all` policy is
   * `for all to authenticated`, and its gist exclusion constraint applies to
   * UPDATE as well as INSERT, so Postgres still guarantees no double-book.
   */
  rescheduleAppointment(appointmentId: string, input: { startsAt: string; bayId: string }): Promise<void>
  markAppointmentReminderSent(appointmentId: string): Promise<void>
}

export type {
  Shop,
  Quote,
  QuoteBundle,
  Customer,
  QuoteOption,
  QuoteEvent,
  QuoteResponse,
  EmailMessage,
  CatalogItem,
  PackageTemplate,
  StockMovement,
  Invoice,
}
